export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  TOURNAMENTS: "/tournaments",
  TOURNAMENT_DETAIL: "/tournaments/:id",
  LEADERBOARD: "/leaderboard",
  ACHIEVEMENTS: "/achievements",
  WALLET: "/wallet",
  MARKETPLACE: "/marketplace",
  MESSAGES: "/messages",
  NOTIFICATIONS: "/notifications",
  SOCIAL: "/social",
  FRIENDS: "/friends",
  TEAMS: "/teams",
  SETTINGS: "/settings",
  SEARCH: "/search",
  EXPLORE: "/explore",
  LIVE: "/live",
  FLEX: "/flex",
  STORIES: "/stories",
  STORIES_NEW: "/stories/new",
  GAME_ROOMS: "/game-rooms",
  MY_MATCHES: "/my-matches",
  REWARDS: "/rewards",
  SAVED: "/saved",
  TRENDING: "/trending",
  ACTIVITY: "/activity",
  HOW_IT_WORKS: "/how-it-works",
  FAIR_PLAY: "/fair-play",
  FAQS: "/faqs",
  SUPPORT: "/support",
  CONTACT: "/contact",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  REFUND: "/refund",
  REPORT: "/report",
  ADMIN: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_TOURNAMENTS: "/admin/tournaments",
  ADMIN_USERS: "/admin/users",
  ADMIN_PAYMENTS: "/admin/payments",
  ADMIN_MATCHES: "/admin/matches",
  ADMIN_LEADERBOARD: "/admin/leaderboard",
  ADMIN_MARKETPLACE: "/admin/marketplace",
  ADMIN_GAME_ROOMS: "/admin/game-rooms",
  ADMIN_ACHIEVEMENTS: "/admin/achievements",
  ADMIN_REGISTRATIONS: "/admin/registrations",
  ADMIN_REWARDS: "/admin/rewards",
  ADMIN_ROLES: "/admin/roles",
  ADMIN_ANALYTICS: "/admin/analytics",
  ADMIN_SUPPORT: "/admin/support",
} as const;

export function toRoute(base: string, id: string | number): string {
  return base.replace(":id", String(id));
}
